server:
  port: 8081
  servlet:
    context-path: /auth

spring:
  datasource:
    url: jdbc:h2:mem:oauth
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console

debug: true
#logging:
#  level: debug